# Name of action
name: Deploy to Vultr

on:
    push:
        branches: [prod]

jobs:
    Setup:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                node-version: [16.14.2]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm i
              env:
                  CI: true
    Deploy-Bot:
        runs-on: ubuntu-latest
        needs: Setup
        if: github.ref == 'refs/heads/prod'
        steps:
            - name: Deploying to Vultr
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd ${{ secrets.PATH }}
                      git pull
                      export NVM_DIR=~/.nvm
                      source ~/.nvm/nvm.sh
                      npm prune
                      npm ci
                      npm audit fix
                      pm2 reload 2
